name: Node.js metalsmith CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: node index.js

    - run: .github/scripts/install_apache2.sh
    - run: .github/scripts/configure_apache2.sh

    # Do a lookup on local.dev hostname set above 
    - run: sudo apache2ctl configtest

    # Check Apache Version
    - run: sudo apache2 -v


    - run: curl -vsf 'http://localhost:80/'

    - run: curl -vsf 'http://localhost:80/phpinfo.php' -o phpinfo.html

    - name: Save phpinfo
        uses: actions/upload-artifact@v1
        with:
          name: phpinfo
          path: phpinfo.html

          

