name: Node.js metalsmith CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: node index.js

    - name: Install apache2 and php
      run: .github/scripts/install_apache2.sh
    - name: Configure apache2
      run: .github/scripts/configure_apache2.sh

    # Do a lookup on local.dev hostname set above 
    - run: sudo apache2ctl configtest

    # Check Apache Version
    - run: sudo apache2 -v

    # Check phpinfo
    - run: curl -vsf 'http://localhost:80/phpinfo.php' -o phpinfo.html
    - name: Save phpinfo
      uses: actions/upload-artifact@v1
      with:
        name: phpinfo
        path: phpinfo.html

    # Check index page
    - run: curl -vsf 'http://localhost:80/' -o index.html
    - name: Save index
      uses: actions/upload-artifact@v1
      with:
        name: index
        path: index.html

    # start selenium
    - run: pip install selenium requests

    # test selenium
    - run: python .github/scripts/check_site.py
