name: Node.js metalsmith CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: node index.js

    - run: .github/scripts/install_apache2.sh

    - run: curl -vsf 'http://localhost:80/'

    # Do a lookup on local.dev hostname set above 
    - run: sudo apache2ctl configtest

    # Check Apache Version
    - run: sudo apache2 -v

    # Check PHP Version
    - run: sudo php -v
